name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::891377349958:role/kintai-kanri
          aws-region: ap-northeast-1

      - name: Deploy to S3
        run: aws s3 sync . s3://kintai-kanri --exclude ".git/*" --exclude ".github/*" --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E3B8S2D0Z4CMWP --paths "/*"